import { ThemeProvider } from "@/components/theme";
import { ReactQueryProvider } from "@/react-query/provider";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/server/auth";
import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import { Toaster } from "sonner";
import ClientProviders from "./client-providers";
import "@/styles/globals.css"; // Import Tailwind CSS global styles
import Navbar from "@/components/Navbar";
import { CheckInProvider } from "@/contexts/CheckInContext";

const jakarta = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Grouple",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jakarta.className} bg-black`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          <ClientProviders session={session}>
            <ReactQueryProvider>
              <CheckInProvider>
                <Navbar />
                {children}
              </CheckInProvider>
            </ReactQueryProvider>
          </ClientProviders>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
